### ISSUE TITLE
Linux compile error and solution

### ISSUE THREAD

**Issue by ShneekeyTheLost** [mcgrew/dwrandomizer#105]
Linux compile instructions, as currently written, will give an error about C++ 11. On the very helpful Discord, someone showed me how to solve.

The make file produced has an incorrect version number and doesn't have a flag properly listed. 

Quick fix:

change your qmake to

qmake DEFINES+="DWR_RELEASE" CONFIG+="c++11" ../dwrandomizer.pro

That adds the flag to the make file and updates the release versioning. 

It would be appreciated to update the Make file when you get a chance so that the listed instructions in the Readme works again.

**Comment by bunder2015** [comment]
Building on current gentoo appears to work for me...

```
git clone https://github.com/mcgrew/dwrandomizer.git
cd dwrandomizer
git checkout a89edb53b9279994023d158619d5ee6844be2963 -b build-468
mkdir build
cd build
qmake ../dwrandomizer.pro
make
```

**Comment by mcgrew** [comment]
I have added this flag to the release script.
