### ISSUE TITLE
Have text boxes appear when overing an option

### ISSUE THREAD

**Issue by GB127** [mcgrew/dwrandomizer#110]
Would be helpful if a textbox appeared when hovering on the option.

For example, I did not understand fully what the two goals options meant, and I had to ask for clarifications on the discord. Would be helpful if we could have a textbox when I put my mouse on it, kinda like Z1R if I recall the application correctly.

**Comment by mcgrew** [comment]
It is explained somewhat in the readme, but I agree tooltips would be nice. I'd like to add them, but I haven't looked into how to implement them with Qt yet. It's definitely on my radar.

**Comment by mcgrew** [comment]
I have added flag descriptions to the alpha build of 3.0. Hopefully this will be sufficient.
