### ISSUE TITLE
Swamp surrounding Tantegel Castle

### ISSUE THREAD

**Issue by gameboy9** [mcgrew/dwrandomizer#12]
Sparkover and I in our first race on June 1 had an issue where Tantegel Castle was surrounded by a swamp and we couldn't get out without dying. (11 HP with 6 spaces before getting out)  I really don't think we should have seeds that start out that way.  This was done in version 1.0, but I don't think you've done anything to the randomized map making since then.

**Comment by mcgrew** [comment]
I've seen this before, but some players consider it a challenge. I've seen jkoper and ouijawii both trying to run seeds like this, so I'm not sure if it's something I should remove.

**Comment by gameboy9** [comment]
Interesting.  I have to applaud those two for suffering through that!  

However, my opinion is that if Tantegel is surrounded by a bunch of swamp... then the castle should be "overruled" to one "other than swamp" square surrounding the castle. (I think I didn't explain that too well, so I attached a text file below)  Then the players can at least level up to a point where they can get out of the swamp without dying 87 times like the seed Sparkover and I were on.  I really think we should do something like this if we decide to run a tournament in the future, because I'm sure that contestants would ask for a reseed if they ran into a scenario like that.
[swamp.txt](https://github.com/mcgrew/dwrandomizer/files/298790/swamp.txt)

**Comment by mcgrew** [comment]
I think in any tournaments a rule could be in place to allow a reseed if both players agree to it. It might be desired for other reasons as well.

That said, I'll consider this, as it's not a terrible idea.

**Comment by gameboy9** [comment]
Seeing that I am clearly of the minority opinion here, and since the majority do not think this is a bug, I am withdrawing this issue.  Thanks for considering it though!  :)
