### ISSUE TITLE
Major bug - Random Stairs can make Grave of Garinham incompletable (potential softlock)

### ISSUE THREAD

**Issue by skins4thewin** [mcgrew/dwrandomizer#129]
Just had a seed where I might be softlocked due to Random Stairs.  Since there's only one staircase on the initial Grave of Garinham floor, it can lead to the staircase in the middle of the 3rd floor which leads to nothing.  This is exactly what just happened to me in a seed, meaning the final two chests are completely inaccessible.  Is this accounted for in Chest logic?

By the way, am not sure how to mark a post with the Bug label.  I don't see an option to do so.  How do you do that?  Thx in advance.

**Comment by mcgrew** [comment]
Did you check other caves? You should be able to reach those chests via other cave entrances (mountain cave, tablet cave).

**Comment by mcgrew** [comment]
Considering there has no response I am assuming this issue is resolved.

**Comment by skins4thewin** [comment]
Lol hell I posted this bug like a year or more ago.  I honestly don't even remember what the issue was...

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
