### ISSUE TITLE
Drakeema EXP/GP check

### ISSUE THREAD

**Issue by gameboy9** [mcgrew/dwrandomizer#13]
According to the SNES and GBC versions, Drakeemas score 20 XP and 25 GP, not 12XP and 20GP as programmed in the current randomizer.  Is there another version that has the reduced Drakeema XP?

**Comment by mcgrew** [comment]
In the original game the values were 11XP and 20G (functionally 19G because of the way the game calculates gold drops). Not sure where the 12/20 came from - probably an oversight. I'll fix this in 1.1 and check the other values to make sure I didn't miss any more.

Thanks.

**Comment by mcgrew** [comment]
Fixed by commit a3e011c40765901be48026447344cd6544b6e97f
