### ISSUE TITLE
Ways to speed up the game

### ISSUE THREAD

**Issue by gameboy9** [mcgrew/dwrandomizer#14]
I found a few ways you can speed up the randomizer.  This is totally up to you if you want to implement this or not... by my estimation, it will speed up the game by an average of about 3 minutes / game.

This uses the ROM addresses found in the standard headered Dragon Warrior (U) (PRG0) [!].nes file.

E41A, B, C -> EA EA EA
E44D, E, F -> EA EA EA
C53F, 40, 41 -> EA EA EA

This will instantly load the monster to fight, saving approximately 1.3 seconds / encounter.

EF49 - 05 -> 01 (One monster flash instead of 5 when the enemy is hit, saving 8 frames / hit.  This does the same when the enemy casts a spell, but it doesn't speed up spell casting because it waits for the spell sound to finish)

ED45 - 08 -> 01 (One shake of the screen instead of eight when the player is hit, saving 14 frames / hit)

4D3C = 00
4D4B, 4D, 4F, 51, 53, 55, 57 = 01
These royally speeds up the death tune, trimming 4+ seconds every time you die.

463F, 41, 43, 45, 47, 49, 4B, 4D = 01
4653, 55, 57, 59, 5B, 5D, 5F, 62 = 01
Speeds up the level up tune, saving nearly 2 seconds every time you level up.

472A, C, and E = 01 - Speeds up the won battle tune... it saves a little bit of time, but it's somewhat negligible.

Again, I'll leave it up to you if you want to implement any of this, especially the musical speedups(I would like to figure out how to skip the tune entirely), but I'm hopeful that you will.  :)  But if not, you can promptly close the issue; I would totally understand.

**Comment by gameboy9** [comment]
OK, I have one more for you: 
0x7A43, 44, 45 -> EA EA EA

This will ROYALLY speed up the text.  Instead of printing the text one character at a time, it will print the text one LINE at a time, saving an average of 15 frames / line of text.  You'll have to read quickly, but this should really speed up the battles more than what I've proposed above.

**Comment by mcgrew** [comment]
I like some of these changes a lot. I'll probably save them for a later release, as I'd like more time to test them, but I'll likely implement most if not all.

Thanks!

**Comment by gameboy9** [comment]
That's a good idea... make sure everything's in order first.  I can tell you that opening doors seems to take an extra second or two, but it doesn't crash the game.  

One more speedup... basically cutting the "you win tune" off... 0x4724 = 0x01 should cut the victory tune by about a second, releasing you back to exploration one second earlier.  Multiply that by 120 battles, and you have 2 minutes shaved in total...

**Comment by gameboy9** [comment]
I found an issue with the dungeon music... it's acting a bit strange.  It doesn't affect gameplay, however.  Please see my June 9 Twitch stream for details.

**Comment by mcgrew** [comment]
I checked it out, and it's pretty hilarious, but I'll look into fixing it. What do you think of the changes thus far?

**Comment by gameboy9** [comment]
I think they're pretty good.  I think you sped up the music better than I did... I did it "get it done as quickly as possible", but you sped it up so the structure of the tune was maintained.

**Comment by gameboy9** [comment]
OK, I think I might have figured it out.

In lines 533, 534, and 535 of dwrandomizer.py...

0x341a: (0xea, 0xea, 0xea), <------- Should be e41a
      0xe44d: (0xea, 0xea, 0xea), <------- This is OK
      0xc35f: (0xea, 0xea, 0xea), <------- Should be c53f (the 2nd and 3rd characters need to be switched)

I'm thinking this might have screwed up the dungeon music as well.  At least that's what I'm hoping anyway.

Thanks again!

**Comment by gameboy9** [comment]
I wanted to create a pull request, but I couldn't figure it out, so I'll attach a replacement dwrandomizer.py that you can look at. (I have to ZIP this... GitHub rules)

I figured out a way to speed up the "level up" music without it sounding weird at the end(it turned out that we only needed to change one byte, 0x463b!), I corrected the dungeon music, and I eliminated the pause from the battle music to the "you're dead" music.(I did NOT change the actual "you're dead" music itself)

After that, maybe a few more tests and I think we're good to go with this issue.  I suggest that it NOT be the default though; I think there was significant feedback of players not wanting to play with the speed hacks.  Thanks again!  :)

[dwrandomizer.zip](https://github.com/mcgrew/dwrandomizer/files/355577/dwrandomizer.zip)

**Comment by mcgrew** [comment]
Closing this issue since it is now implemented in master.

**Comment by Niamek** [comment]
> EF49 - 05 -> 01 (One monster flash instead of 5 when the enemy is hit, saving 8 frames / hit. This does the same when the enemy casts a spell, but it doesn't speed up spell casting because it waits for the spell sound to finish)

Reading this made me wonder if something similar can be done for the annoying flashes of some of the spells. Since it's the whole screen that blinks, it can be quite aggressive.
