### ISSUE TITLE
v1.1 crash

### ISSUE THREAD

**Issue by gameboy9** [mcgrew/dwrandomizer#15]
I can't seem to get a new version out in version 1.1.  Can you take a look at this error, please?

...
Setting enemy HP to approximate remake levels...
Lowering MP requirements to remake levels...
Setting XP requirements for levels to 50% of normal...
Moving REPEL to level 8...
Ultra randomizing level spells are learned...
Updating title screen...
Traceback (most recent call last):
  File "dwrandomizer.py", line 996, in <module>
    main()
  File "dwrandomizer.py", line 763, in main
    randomize(args)
  File "dwrandomizer.py", line 983, in randomize
    rom.update_title_screen(args.seed, flags)
  File "dwrandomizer.py", line 688, in update_title_screen
    new_text += b'\x5f' * needed_bytes + padding(32 - needed_bytes) + b'\xfc'
  File "dwrandomizer.py", line 669, in <lambda>
    padding = lambda s: struct.pack('BBB', 0xf7, s, 0x5f)
struct.error: ubyte format requires 0 <= number <= 255

Thanks!

**Comment by mcgrew** [comment]
Whoops! 

This happens when formatting the new title screen and a short seed number is used. I've pushed a fix (aa7ca2379b7bf31975390a698abf7d0c1e2e9d57) and I'll release a new binary this evening.
