### ISSUE TITLE
Menu wraparound

### ISSUE THREAD

**Issue by gameboy9** [mcgrew/dwrandomizer#16]
Here's another enhancement you can implement if you want to.  The Python code is as follows:

0x69f0: (0x4c, 0xa0, 0xbe, 0xea),
0x6a33: (0x4c, 0xba, 0xbe, 0xea),
0x7eb0: (0xa5, 0xd9, 0xd0, 0x13, 0xad, 0xe5, 0x64, 0xe9, 0x03, 0x4a, 0xe9, 0x01, 0x85, 0xd9, 0x0a, 0x69, 0x02, 0x8d, 0xf3, 0x64, 0x4c, 0x27, 0xaa, 0x4c, 0xe4, 0xa9),
0x7eca: (0xc5, 0xd9, 0xd0, 0x0c, 0xa9, 0x01, 0x85, 0xd9, 0xa9, 0x04, 0x8d, 0xf3, 0x64, 0x4c, 0xe4, 0xa9, 0x4c, 0x27, 0xaa),

Basically if you press up on the first item, instead of staying on the first item, it goes to the last item instead, and vice versa.  It's mainly useful when you have to cast Hurtmore or Healmore, but it really helps out the interface.  I'd say this trims... maybe 30-60 seconds from the average randomizer time.

The only problem with this is that when you wraparound, the pointer from the first/last item might stay on the screen.  It's only a minor graphical issue though, and therefore it might not matter when it comes to racing, because people want to cast the spells quickly anyway.

**Comment by gameboy9** [comment]
I figured out the menu wraparound with no graphical glitches at all!

This actually should go to all randomizers, not just the speed hacks.  The reason I'm claiming this is because I have discovered that wraparound menus are in use in the SNES and GBC remixes of Dragon Quest.

The python code is below:

      # wraparound menu
	  0x69f0: (0x4c, 0xa0, 0xbe, 0xea),
	  0x6a33: (0x4c, 0xd0, 0xbe, 0xea),
	  0x7eb0: (0xad, 0xe5, 0x64, 0xc9, 0x04, 0xf0, 0x1e, 0x20, 0x30, 0xab, 0xa5, 0xd9, 0xd0, 0x14, 0xad, 0xe5, 0x64, 0xe9, 0x03, 0x4a, 0xe9, 0x00, 0x85, 0xd9, 0x0a, 0x6d, 0xf3, 0x64, 0x8d, 0xf3, 0x64, 0x4c, 0x27, 0xaa, 0x4c, 0xe4, 0xa9, 0x60),
	  0x7ee0: (0x48, 0xad, 0xe5, 0x64, 0xc9, 0x04, 0xf0, 0x20, 0x20, 0x30, 0xab, 0x68, 0xc5, 0xd9, 0xd0, 0x15, 0xa9, 0x01, 0x85, 0xd9, 0xad, 0xf3, 0x64, 0x29, 0x01, 0xd0, 0x02, 0x69, 0x02, 0x69, 0x01, 0x8d, 0xf3, 0x64, 0x4c, 0xe4, 0xa9, 0x4c, 0x27, 0xaa, 0x68, 0x60),

**Comment by Kronoan** [comment]
That sounds cool! If McGraw implements that in the next version that would be great!

**Comment by mcgrew** [comment]
This is good, but there's still a glitch on the select message speed screen. Also when you get some time I'd like to talk about what this patch is actually doing.

**Comment by Niamek** [comment]
Maybe a better alternative is to change the order of the spells: the most used on the top, the least used on the bottom?

**Comment by gameboy9** [comment]
Sure thing.
The first two lines jumps to a function to the bottom two lines, depending on the direction you're coming from.  

The third line:
0xad, 0xe5, 0x64, // LDA 64e5
0xc9, 0x04, // CMP #04 (I think that means the first line)
0xf0, 0x1e, // BEQ -> RTS
0x20, 0x30, 0xab, // JSR $AB30, an ENIX programmed function that clears out the previous arrow
0xa5, 0xd9, // LDA $00D9
0xd0, 0x14, // BNE $BEC2 (2nd JMP statement; you're not at the beginning of the menu, so continue per normal)
0xad, 0xe5, 0x64, // LDA $64E5 - I think that's the length of the menu
0xe9, 0x03, // SBC 03 (plus another one) - required to get to the last item I think
0x4a, // LSR (required per above)
0xe9, 0x00, // SBC 00 (plus another one, required per above)
0x85, 0xd9, // STA $00D9
0x0a, // ASL
0x6d, 0xf3, 0x64 // ADC $64F3
0x8d, 0xf3, 0x64, // STA $64F3
0x4c, 0x27, 0xaa, // JMP $AA27 (so I basically placed the cursor on the "last - 1" line and am pushing down in the menu)
0x4c, 0xe4, 0xa9, // JMP $A9E4 (act like you're going up, per usual)
0x60 RTS

-----------------------------------------
The fourth line:
0x48, // PHA (need to save this for later)
0xad, 0xe5, 0x64, // LDA $64E5 - Load menu position
0xc9, 0x04, // CMP #$04 (are you at the beginning)
0xf0, 0x20, // BEQ $BEF8 (if so, carry on)
0x20, 0x30, 0xab, // JSR $AB30 (clear the cursor)
0x68, // PLA (bring the accumulator we pushed back)
0xc5, 0xd9,  // CMP $00D9
0xd0, 0x15, // BNE $BEF5 (continue with the down menu input)
0xa9, 0x01, // LDA #$01
0x85, 0xd9, // STA $00D9
0xad, 0xf3, 0x64, // LDA $64F3
0x29, 0x01, // AND 01
0xd0, 0x02, // BNE $BEED (if the menu is "double spaced", then we need to account for that via the line below)
0x69, 0x02, // ADC 02
0x69, 0x01, // ADC 01
0x8d, 0xf3, 0x64, // STA $64F3
0x4c, 0xe4, 0xa9, // JMP $A9E4 - we went to the 2nd item of the menu and turning it into an upward input
0x4c, 0x27, 0xaa, // JMP $AA27 (continue with downward input)
0x68, // PLA
0x60), // RTS

It's been a while since I programmed this, so I'm probably forgetting a few things, but hopefully this helps out.

**Comment by gameboy9** [comment]
Niamek, it's an interesting thought, but my opinion is that since the order of spells are so ingrained in our heads, we probably would get severely thrown off by the change of spell order.  Although I suppose we could get used to it.

Also, if DW2 is any indication, it will probably be VERY hard to program such a change in the first place.

**Comment by Niamek** [comment]
gameboy9, you got a point.

I just threw that idea if fixing the menu wrap around is impossible. Hopefully it's fixable!

**Comment by gameboy9** [comment]
OK, try this:

`  def menu_wrap(self):
    self.add_patches({ #implement up/down wraparound for the menu
      0x69f0: (
        # f059: 
          0x4c, 0xa0, 0xbe,         # JMP $BEA0
          0xea,                     # NOP
      ),
      0x6a33: (
        # 6a23: 
          0x4c, 0xd0, 0xbe,         #JMP #BED0
          0xea,                     # NOP
      ),
      0x7eb0: (
        # 7ea0:
		  0xa5, 0x45,				# LDA $0045
		  0xf0, 0x5c,				# BEQ
          0xad, 0xe5, 0x64,         # LDA $64E5 
          0xc9, 0x04,               # CMP #$04
          0xf0, 0x1e,               # BEQ  
          0x20, 0x30, 0xab,         # JMP $AB30 
          0xa5, 0xd9,               # LDA $00D9
          0xd0, 0x14,               # BNE 
          0xad, 0xe5, 0x64,         # LDA $64E5
        # 7eb0:
          0xe9, 0x03,               # SBC #$03
          0x4a,                     # LSR
          0xe9, 0x00,               # SBC #$00
          0x85, 0xd9,               # STA $00D9 
          0x0a,                     # ASL
          0x6d, 0xf3, 0x64,         # ADC $64F3 
          0x8d, 0xf3, 0x64,         # STA $64F3
          0x4c, 0x27, 0xaa,         # JMP $AA27
        # 7ec0: 
          0x4c, 0xe4, 0xa9,         # JMP $A9E4
          0x60,                      # RTS
		  0xa5, 0xd9, 0x60
      ),
      0x7ee0: (
        # 7ed0
          0x48,                     # PHA
		  0xa5, 0x45,				# LDA $0045
		  0xf0, 0x3b,				# BEQ
          0xad, 0xe5, 0x64,         # LDA $64E5 
          0xc9, 0x04,               # CMP #$04
          0xf0, 0x20,               # BEQ  
          0x20, 0x30, 0xab,         # JSR $AB30
          0x68,                     # PLA
          0xc5, 0xd9,               # CMP $00D9
          0xd0, 0x15,               # BNE
          0xa9, 0x01,               # LDA #$01
          0x85, 0xd9,               # STA $00D9
          0xad, 0xf3, 0x64,         # LDA $64F3
          0x29, 0x01,               # AND #$01
          0xd0, 0x02,               # BNE
          0x69, 0x02,               # ADC #$02
          0x69, 0x01,               # ADC #$01
          0x8d, 0xf3, 0x64,         # STA $64F3
          0x4c, 0xe4, 0xa9,         # JMP $A9E4
          0x4c, 0x27, 0xaa,         # JMP $AA27
          0x68,                     # PLA
          0x60                      # RTS
      ),
	  0x7f10: (
		0xa5, 0xd9, 0xf0, 0xf9, 0x4c, 0xe4, 0xa9
	  ),
	  0x7f20: (
		0x68, 0xc5, 0xd9, 0xf0, 0xe8, 0x4c, 0x27, 0xaa
	  )
    })
`

**Comment by mcgrew** [comment]
This is implemented in 1.3-rc1.
