### ISSUE TITLE
Gold adjustment suggestion

### ISSUE THREAD

**Issue by gameboy9** [mcgrew/dwrandomizer#17]
This is strictly another suggestion, and not a bug.  I can totally understand this not being implemented, but here goes.
0xea51: (0xad, 0x07, 0x01, 0xea, 0xea),

This automatically gives out the maximum gold for all encounters.  You will have to decrease all the monster gold by 1 if you implement this.  The reason I'm placing this suggestion down is because in the remix, monsters always give out the maximum gold, so this will replicate that rule change.

I'd also like to suggest that if the XP is halved, the gold requirements for weapons, items, and inns should be halved as well.  This increases the chances of "earning" the Silver Shield, etc. instead of hoping to gold grind in Tantegel.

Thanks for considering this.

**Comment by mcgrew** [comment]
Alright, it's something to look into.

As for weapon prices, I'll have to figure out where those are stored in the rom, but it's something to think about.

**Comment by mcgrew** [comment]
This has been implemented.
