### ISSUE TITLE
Monster adjustments

### ISSUE THREAD

**Issue by gameboy9** [mcgrew/dwrandomizer#18]
I'm sorry I keep adding issues, Mcgrew.  This one regards to the Droll HP.  You currently have it set for 43 HP, which is the HP listed in the Dragon Warrior Strategy Wikipedia.  However, after some research on the SNES rom, I discovered that ROM address 0x0BDAB3 listed the Droll HP at 35.  There are two places on the internet that further confirms that number, and I'm thinking that's the case for the small 18 XP reward Drolls give out.

Can you look into this one as well, please?  Thanks once again; it's very much appreciated!  :)

**Comment by gameboy9** [comment]
Found one other issue... the Werewolf only has 95 XP and 155 GP, not 120 XP and 185 GP.  (The wizard has this; you have that one correctly)

**Comment by mcgrew** [comment]
Thanks. I'll take a look at those numbers. I have the GBC cart, so I'll try to see what the droll HP is on there.

**Comment by mcgrew** [comment]
I played through the GBC version and confirmed this. Fixed.
