### ISSUE TITLE
Charlock Obstructed by Mountain

### ISSUE THREAD

**Issue by caleb** [mcgrew/dwrandomizer#19]
Hi!

I was watching a race of `dwrandomizer` and saw that there was a mountain blocking Charlock so players couldn't enter.

Just thought I'd give you a heads up, thanks for this fun program!

Caleb

**Comment by mcgrew** [comment]
I got the seed number from NESCardinality, putting it here so I won't lose it: 9495296479

I'll see if I can figure out what's going on.

**Comment by mcgrew** [comment]
I found the problem. It has been fixed.
