### ISSUE TITLE
No good path

### ISSUE THREAD

**Issue by gameboy9** [mcgrew/dwrandomizer#2]
Using the most recent DW Randomizer (0.9.4, released on 12/30/2015), I did a seed of 1049683387 with no switches, started at the King's Room per usual, then when I went down the stairs, instead of floor 1 of Tantegel Castle, I wound up in Erdrick's Cave.  I got the Stones Of Sunlight, but was unable to continue past this point.

When I tried it with seed 21626551, the stairs took me straight to Kol, but when I left Kol, I went back to the King's room.  Once again, I'm stuck.  :(

Thanks for looking into this!

**Comment by gameboy9** [comment]
The latest pathfinding.py fixes this issue, but now I think we have an unwinnable path with seed 1190581209... 

Tantegel's stairs(Stones Of Sunlight guy) =  Garin's Grave
Garinham's Stairs -> "stones of sunlight guy"
Northern Shrine -> Rainbow Drop guy
Erdrick's Cave -> Rock Mountain Cave
Swamp Cave -> Erdrick's Cave
Rock Mountain Cave -> Northern Shrine

I'm guessing both of the caves in the southern island are swamp caves.  :(

**Comment by mcgrew** [comment]
Sorry, I'm bad about checking these.

For your first issue, there was a problem with the code that was causing it to break the game very badly. I pushed a fix for this on Dec. 31.

As for your second issue, there was a problem where caves were not being properly checked. This was fixed on Jan 4.

Thanks for letting me know.
