### ISSUE TITLE
1.2-beta-2016.08.02 crash

### ISSUE THREAD

**Issue by gameboy9** [mcgrew/dwrandomizer#21]
I'm crashing because there's no "border_tile_patch"... please see below.

... dwrandomizer.py -U -F -H dw1.nes

DWRandomizer 1.2-beta-2016.08.02
Randomizing dw1.nes using random seed 551353823...
Verifying checksum...
Processing Dragon Warrior PRG0 ROM...
Generating new overworld map...
Error: Charlock is obstructed, retrying...
Optimizing compressed map... (Saved 23 bytes)
Traceback (most recent call last):
  File "dwrandomizer.py", line 1007, in <module>
    main()
  File "dwrandomizer.py", line 788, in main
    randomize(args)
  File "dwrandomizer.py", line 901, in randomize
    while not rom.generate_map():
  File "dwrandomizer.py", line 231, in generate_map
    for i in self.owmap.border_tile_patch:
AttributeError: 'WorldMap' object has no attribute 'border_tile_patch'

Thanks!

**Comment by mcgrew** [comment]
I'm not seeing this error. Did you update worldmap.py?

**Comment by gameboy9** [comment]
Oh!  I didn't realize that needed to be updated too!  Sorry, I should have noticed.  Closing the issue.

**Comment by mcgrew** [comment]
No problem.
