### ISSUE TITLE
Adjust heal and hurt to remix values

### ISSUE THREAD

**Issue by gameboy9** [mcgrew/dwrandomizer#24]
This issue proposes a change of heal restoration and hurt damage values to as close as the remix values as we can make it.

0xdbce = 0x07
0xdbd1 = 0x17

This adjusts the heal spell to 23-30.  The SFC remix actually has it at 25-30, but AND #$05 wouldn't work very well.  :(

0xe74a = 0x03
0xe74d = 0x10

This adjusts the hurt spell to 16-19.  The SFC remix is the slightest bit different, 16-20, but, again, placing an AND #$04 wouldn't work so well.  You could make 0xe74d = 0x11 and make it 17-20 if you wanted to.

This change, in addition with putting it in line with the remix, increases the chances of sustainability, especially in the early going if you get one of those spells to start with.

Thanks again for your consideration; it's always appreciated!

**Comment by mcgrew** [comment]
After some discussion in discord, I've decided to go wtih 18-25 for HEAL and 9-16 for HURT for now. This may change before release. Thanks for the help though!
