### ISSUE TITLE
Enhancement: Gwaelin's love in the ranzomized items

### ISSUE THREAD

**Issue by Niamek** [mcgrew/dwrandomizer#29]
So I played a seed today. And I thought about something:

The other day, I talked with some DWR racers, and they told me that they almost never free the princess. So I thought about that during my game today. I thought that if you include that item in the randomized list, it would encourage players to free her and hope for a key item or something?

**Comment by Jaylow7** [comment]
In earlier versions it was possible to find Gwaelin's Love as a chest item. This led to people getting multiples and having a very cluttered item list.  It was removed from that list for simplicity, just like the complete removal of the Silver harp.

**Comment by Niamek** [comment]
Yeah I can see this as a problem.

Maybe either:
- Force a check to avoid collecting duplicates of the key items such as staff of rains and Gwaelin's love when found in chests.
- Randomize Gwaelin's love with the 3 other key items(OW search tile, Dead town thing and Kol search tile)

**Comment by mcgrew** [comment]
This is an interesting thought, and should be possible. I'll get some feedback on this and make a decision.

**Comment by mcgrew** [comment]
I'm closing this since split continents in 2.0 will likely require her to be rescued some of the time in order to find the overworld item.

**Comment by Niamek** [comment]
This is a good compromise.

Looking forward the split continents. :)

**Comment by Niamek** [comment]
Also,

I would still consider adding Gwaelin's love to the randomized pool in a far future.

If Gwaelin's love happens to be the searchable tile on OW. Even if it's hard, or impossible to find it, it won't matter because all other key items can be found and thus finishing is possible.

If Gwaelin's love is not at the searchable tile, that would indicate that the search tile might contain an important item and that the princess might give an important item.
