### ISSUE TITLE
RNG "fixes"

### ISSUE THREAD

**Issue by authorblues** [mcgrew/dwrandomizer#3]
Seems that your code doesn't actually run under 2.7 (at least not on my version) due to syntax errors, so you can probably remove that from your README and just standardize on 3.x. To guard against further changes to RNG algorithms in general, I ported my randomizer's PRNG to Python for you to use if you'd like.

**Comment by authorblues** [comment]
For what it's worth, the inherent "randomness" in this little PRNG is significantly lower than the high quality PRNG provided by Python. You may want to ensure that this meets your personal needs for the DW randomizer, though it works fine for SMW randomizer, so I'm inclined to trust that it should be satisfactory.

**Comment by mcgrew** [comment]
Python 2.x support was never actually intended, it just happened to work. I added that info to the readme after some users reported it working. Perhaps some of the new changes make it not work. 

I think Python's built-in RNG seems fine. I don't see much need to replace it unless there are issues. I'll think about it.

I appreciate the pull request though, it's nice to see interest in the project.

**Comment by mcgrew** [comment]
Since randomizer doesn't seem to work under Python 2 any more, the PRNG differences are no longer a problem. Thus, I'm going to close this issue for now.
