### ISSUE TITLE
Enhancement: Stop a NPC from moving

### ISSUE THREAD

**Issue by Niamek** [mcgrew/dwrandomizer#30]
So I did a seed yesterday, and after collecting the chests, the moving soldier somehow got in front of the door and stayed there for a while.
It could get annoying. I was thinking that, if possible, the prperties of the NPC could be tweaked so that they no longer move? I am thinking about 
- the old man in Graniham(near the item shop)
- the guard near the king throne
- the shopper at that one town where you can get the coordinates of the search tile(forgot the name)

I don't mind about it at all honestly. But I though it would be neat.

**Comment by mcgrew** [comment]
I added these as a possible enhancement for 2.0. #48
