### ISSUE TITLE
Enhancement:  Instant stairs command

### ISSUE THREAD

**Issue by gameboy9** [mcgrew/dwrandomizer#31]
I think all you need is five changes:

B2CE, B3D2, B4C3, B5F4 -> 20 AF D9 (instead of completing movement procedure, jump to the stairs command instead)
DA16 -> 4C C3 B4 -> After checking for stairs, instead of showing a text box, complete the movement

I do foresee two problems:

1)  If you select stairs, you stay in the menu instead of being told that there aren't any stairs.  I personally am OK with this because you would no longer need to select stairs.
2)  The more important issue is running into stairs in normal cave movement.  The mountain cave and the useless stairs on your way to the 5 treasure chests is the biggest offender.  One possible fix, however, is to simply remove those stairs.

There also may be some softlocks... don't implement this yet...

**Comment by mcgrew** [comment]
I've implemented this as an optional flag, but it still needs testing. Can always disable it later.

**Comment by mcgrew** [comment]
These changes do not work. I did notice the king's opening text is garbled a bit though. I'm disabling this for now.
