### ISSUE TITLE
Monster HP Adjustments?

### ISSUE THREAD

**Issue by gameboy9** [mcgrew/dwrandomizer#32]
I'm thinking that the Specter should have 33 HP, not 48 HP that's programmed.  Can you take a look in the GBC/SNES ROM to verify this please?

**Comment by gameboy9** [comment]
I'm also thinking the Poltergeist has 23 HP, not 26, but again, we should double check.  That's not much of an adjustment, but it's still 10+%...

**Comment by mcgrew** [comment]
I'll take a look at these.

**Comment by mcgrew** [comment]
I didn't have time to look in the GBC ROM (not that I know where to look anyway), but I'll go with these for now anyway since it's probably a good balance adjustment.
