### ISSUE TITLE
More speed hacks!

### ISSUE THREAD

**Issue by gameboy9** [mcgrew/dwrandomizer#33]
Fairy flute shortcut:
0x4cb1, 0x4cb3 = 0x01
0x4cc5, 7, 9, and d = 0x01
0x4ce2, 4, 6, 8, a, and c = 0x01

Inn shortcut:
0x46e4, 6, 8, a, c, e = 0x01
0x46f0, 2, 4, 8 = 0x01
0x4701, 3, 5, 7, 9, b, d, f = 0x01
0x4711, 5 = 0x01

Speedy spell casting:
0x436b = 0x9e
0xdb49-e = 0xea
0xdb54-c = 0xea

This is going to speed this game up even further!  Probably another 2+ minutes!

**Comment by mcgrew** [comment]
These have been added in; pending testing.
