### ISSUE TITLE
Monster HP Adjustment for strategic purposes

### ISSUE THREAD

**Issue by gameboy9** [mcgrew/dwrandomizer#34]
As we discussed earlier, adjust the Goldman HP to 30-35, due to the 255 GP maximum.  (it normally awards 600+ and it has 99 HP)

This is probably still up for discussion, but I'm thinking it will open up the game a bit.

... and possibly adjust the Droll HP since it has so little XP?  (maybe 20 or 25 instead of 38?)

**Comment by mcgrew** [comment]
I agree with these changes. It is done.
