### ISSUE TITLE
Monster Zone adjustments (proposed enhancement)

### ISSUE THREAD

**Issue by gameboy9** [mcgrew/dwrandomizer#36]
I did two things with this, one of which was discussed near the end of the tournament, another was somewhat touched with one question.

1)  I made a "zone 1" and "zone 2".  Both of these randomize monsters up to Metal Scorpions.  Zone 1 is placed next to Tantegel's Zone 0 to the north and south (if possible), while zone 2 does the same, except east and west.

2)  Remember me asking if one zone could theoretically dominate the entire map?  Well, with the remaining 59 zones, I "deal out" zones 3-15 like a deck of cards, so no one zone dominates the map.

Please review the attached code and implement if you'd like.

Thanks again!

`  
def randomize_zone_layout(self):
    """
    Randomizes enemy zone layout on the overworld map.
    """
    zones = [3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 
    7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 
    11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15]
    random.shuffle(zones)
	
    #for i in range(len(self.zone_layout)):
    #  self.zone_layout[i] = random.randint(3,15) << 4 | \
    #                        random.randint(3,15)
    for i in range(len(self.zone_layout)):
      self.zone_layout[i] = zones[i * 2] << 4 | zones[(i * 2) + 1]
    # set tantegel's zone to 0
    tx,ty = self.owmap.warps_from[self.owmap.tantegel_warp][1:]
    tantegel_zone_index = (ty // 15 * 8) + tx // 15
    if tantegel_zone_index % 2:
      self.zone_layout[tantegel_zone_index // 2] &= 240 # second nybble
    else:
      self.zone_layout[tantegel_zone_index // 2] &= 15 # first nybble	  
    tz1 = tantegel_zone_index + 8
    tz2 = tantegel_zone_index - 8
    if (tz1 < 64):
      if (tz1 % 2):
        self.zone_layout[tz1 // 2] &= 240 # second nybble
        self.zone_layout[tz1 // 2] += 1
      else:
        self.zone_layout[tz1 // 2] &= 15 # second nybble
        self.zone_layout[tz1 // 2] += 16

    if (tz2 < 64):
      if (tz2 % 2):
        self.zone_layout[tz2 // 2] &= 240 # second nybble
        self.zone_layout[tz2 // 2] += 1
      else:
        self.zone_layout[tz2 // 2] &= 15 # second nybble
        self.zone_layout[tz2 // 2] += 16
	
    tz1 = tantegel_zone_index + 1
    tz2 = tantegel_zone_index - 1
    if (tz1 % 8 != 0):
      if (tz1 % 2):
        self.zone_layout[tz1 // 2] &= 240 # second nybble
        self.zone_layout[tz1 // 2] += 2
      else:
        self.zone_layout[tz1 // 2] &= 15 # second nybble
        self.zone_layout[tz1 // 2] += 32

    if (tz1 % 8 != 7):
      if (tz2 % 2):
        self.zone_layout[tz2 // 2] &= 240 # second nybble
        self.zone_layout[tz2 // 2] += 2
      else:
        self.zone_layout[tz2 // 2] &= 15 # second nybble
        self.zone_layout[tz2 // 2] += 32

  def randomize_zones(self, ultra=False):
    """
    Randomizes which enemies are present in each zone.

    :Parameters:
      ultra : bool
        Whether or not to apply ultra randomization
    """
    new_zones = list()
    if ultra:
      # randomize zone locations
      if self.owmap.generated:
        self.randomize_zone_layout()
      # zone 0-2
      for i in range(0,5):
        new_zones.append(random.randint(0, 6))
      for i in range(0,5):
        new_zones.append(random.randint(0, 13))
      for i in range(0,5):
        new_zones.append(random.randint(0, 13))
      # zones 3-15
      for i in range(0,65):
        new_zones.append(random.randint(0, 37))
      # zones 16-18 (Charlock)
      for i in range(0,15):
        new_zones.append(random.randint(29,37))
      # zone 19
      for i in range(0,5):
        new_zones.append(random.randint(0, 37))

      # randomize forced encounter enemies:
      # Golem, Axe Knight, Blue Dragon, Stoneman, Armored Knight, Red Dragon
      for i in range(3):
        self.encounter_enemies[i] = random.choice((24, 33, 34, 35, 36, 37))
      self.encounter_2_kill[0] = self.encounter_enemies[1]
      self.encounter_3_kill[0] = self.encounter_enemies[2]
    else:
      #zone 0
      for j in range(5): 
        new_zones.append(int(random.randint(0, 6)/2))

      # zones 1-13 (Overworld)
      for i in range(1, 14):
        for j in range(5):
          enemy = random.randint(i * 2 - 2, min(37,round(i*3)))
          while enemy == 24: # don't add golem
            enemy = random.randint(i * 2 - 2, min(37,round(i*3)))
          new_zones.append(enemy)

      #zone 14 - Garin's Grave?
      for j in range(5): 
        new_zones.append(random.randint(7, 17))

      #zone 15 - Lower Garin's Grave
      for j in range(5): 
        new_zones.append(random.randint(15, 23))

      # zone 16-18 - Charlock
      for i in range(16, 19):
        for j in range(5):
          new_zones.append(random.randint(13+i, 37))

      # zone 19 - Rimuldar Tunnel
      for j in range(5):
        new_zones.append(random.randint(3, 11))
    self.zones = new_zones
`

**Comment by mcgrew** [comment]
This has been implemented in master.
