### ISSUE TITLE
Silver Harp not found

### ISSUE THREAD

**Issue by gameboy9** [mcgrew/dwrandomizer#37]
Please check out the ROM below.  I don't think I can find the Silver Harp here.  Thanks.

[DWRando.ACGHIMPTWZf.1542288942.PRG0.nes.zip](https://github.com/mcgrew/dwrandomizer/files/617675/DWRando.ACGHIMPTWZf.1542288942.PRG0.nes.zip)

**Comment by mcgrew** [comment]
Sure enough, the harp is in Charlock in that one. I'll take a look.

**Comment by mcgrew** [comment]
This is fixed in master. Slight mixup with indices.
