### ISSUE TITLE
I forget how I got this to work before ...

### ISSUE THREAD

**Issue by Kronoan** [mcgrew/dwrandomizer#41]
Hey, can anyone help me with a step-by-step way to use Python 3.5.2 to use this randomizer? I did it before but I lost my instructions and I can't remember or figure out how to get it working now. Thanks guys!

**Comment by Kronoan** [comment]
I figured out a workaround. But I'd still appreciate a step-by-step guide of using the randomizer in Python normally. Thanks!

**Comment by mcgrew** [comment]
Closing this since the rewrite is in C, obviously how to use python won't be helpful any more.
