### ISSUE TITLE
Shuffle Searchable Items Flag Always Set

### ISSUE THREAD

**Issue by Kronoan** [mcgrew/dwrandomizer#42]
Hey there. I wanted to bring an issue with the randomizer to your attention McGrew. Whether or not the box marked Shuffle Searchable Items is ticked or not, the randomizer always sets the I Flag, and randomizes the co-ordinates for the 3rd searchable item spot. I feel this must be a bug, and I would like to see if you can try to correct it for the next build. And I really like the new GUI version of the randomizer!

**Comment by Entroper** [comment]
https://github.com/mcgrew/dwrandomizer/blob/master/randomizer_gui.py#L121

I think this is the issue.  `no_search_items` here, vs. `no_searchitems` in the main script.

**Comment by mcgrew** [comment]
Closing this since the rewrite for 2.0 will fix it.
