### ISSUE TITLE
Shields not adding to defense power in 1.3 RC2...

### ISSUE THREAD

**Issue by gameboy9** [mcgrew/dwrandomizer#43]
I think that the shield isn't adding to the defense power in 1.3 RC2.  Can you take a look, please?

**Comment by Kronoan** [comment]
Oh no! Let's hope that gets fixed!

**Comment by mcgrew** [comment]
Yep, you're right. I'll look into it.

**Comment by mcgrew** [comment]
Latest commits have fixed this.
