### ISSUE TITLE
Sprite swaps

### ISSUE THREAD

**Issue by mcgrew** [mcgrew/dwrandomizer#47]
Main character sprite swaps. Current ideas:
- Gwaelin
- Link
- Trogdor

**Comment by Niamek** [comment]
Basically all OW sprites would make great character sprite swap. :)

I'm not sure, but maybe Dragon Lord too would be a possible.

**Comment by mcgrew** [comment]
I found the palette info for the main character last night, so that's good news for this enhancement. Bed news is some NPCs use the same palette, but that might be something I end up ignoring (unless I can figure out how to change NPC pallettes, maybe not worth it)

**Comment by mcgrew** [comment]
This work is done enough for 2.0, though I'm sure future versions will add more sprite options.
