### ISSUE TITLE
NPC freezing

### ISSUE THREAD

**Issue by mcgrew** [mcgrew/dwrandomizer#48]
A few NPCs can get extremely annoying due to moving around. These can affect race outcomes and probably shouldn't. Consider freezing their movement. 

Current list:
- Old man in item shop in Garinham
- Soldier in the throne room
- Weapon shop owner in Cantlin

**Comment by Jaylow7** [comment]
While you're at it, how about one more?

Soldier in Tantegel treasure room.

I've had him block me for 5+ minutes trying to leave that room after a gold grind.

**Comment by mcgrew** [comment]
Not really "freezing", but the issue is fixed. I'll think about the treasury soldier.
