### ISSUE TITLE
Music disable option

### ISSUE THREAD

**Issue by Myriachan** [mcgrew/dwrandomizer#5]
I noticed that there's no hack to disable music.  Here's a patch that is going somewhat in the right direction, but doesn't fully work.

Change the byte pattern 303A0A85 (.nes file offset 0x41B6 in my ROM) to 10393038.

This causes only sound effects to play, but isn't perfect.  When exiting a town, the noise channel will continue until the next sound is played.  Also, the game freezes after completing a battle.  The patch clearly needs more work.

I can only hope that this helps! =^-^=

**Comment by mcgrew** [comment]
I can see this being something users might want. There's probably a better way to handle disabling music though. I'll look into it (and possibly music randomization) for 1.1.

**Comment by Jaylow7** [comment]
I agree with Myria, this is a thing we have in the zelda 1 randomizer and would be nice to have here. The travel/town music is nice, but the very repetitive battle music gets a bit old after 3+ hours...

**Comment by mcgrew** [comment]
Moving this to 1.2 as I'm having trouble figuring it out. I've managed to mess with the town/overworld/dungeon music, but the battle music is elusive.

**Comment by Kronoan** [comment]
I'm sure you can figure it out eventually man! You're a great coder!

**Comment by mcgrew** [comment]
This is mostly implemented in 2.0, though it still needs some work. Battle music isn't disabled, and music does play after using an inn.
