### ISSUE TITLE
Sheild def. value not calculated 

### ISSUE THREAD

**Issue by kiatsushi** [mcgrew/dwrandomizer#51]
I'm on 1.3 rc2 and no matter what shield I buy it does not increase my defense value at all.

**Comment by mcgrew** [comment]
That should be fixed in commit c893d8d580eb598b9a60ea0d2e921a06a5b1f97c if you want to try that.

I'm currently doing a rewrite for the 2.0 release, where it should be fixed as well.

**Comment by kiatsushi** [comment]
Awesome, thank you!


________________________________
