### ISSUE TITLE
Easier Seed confirmation on screen

### ISSUE THREAD

**Issue by Niamek** [mcgrew/dwrandomizer#57]
So I played a version of Super Metroid randomizer and they got something very interesting for seed confirmation. I appreciate the seed number on the screen. That makes things easier for replicating a seed if someone want to retry or something. However, to check if it's the right seed. Currently with DWR, it's the ips checksum (IIRC) that is used as a check.

I'd try to do something different. See this picture from super metroid randomizer: :
![image](https://user-images.githubusercontent.com/15385566/29487833-bcf4e6ae-84cd-11e7-9b20-e749305e1501.png)

The seed confirmation used is 4 names of enemies in a specific order. Real simple to check.
Randomizer link: https://itemrando.supermetroid.run/

There is also something similar in a link to the past:
![image](https://user-images.githubusercontent.com/15385566/29487881-582c41ee-84ce-11e7-998c-dbe19592bdf0.png)
The seed confirmation used is 4 sprites in a specific order. Again easy to check. (However the seed number doesn't seems to be displayed there. If I recall correctly, it's displayed elsewhere.)
Randomizer link: http://vt.alttp.run/

Currently in DWR, it's like this:
![image](https://user-images.githubusercontent.com/15385566/29487898-bf790fe4-84ce-11e7-9b2a-af40d661e290.png)

I really like the flag and the seed number displayed, but this addition would be awesome. :) 

Maybe take something from super metroid with having 4 "something" displayed" or alttp with sprites to make it easier to confirm with others racers? 

I know the ips copy method is doing the job. But I'd welcome this feature. That way you'd confirm you have the right file and the right seed in one go.

**Comment by mcgrew** [comment]
This is difficult to implement given the limits of the NES and not really necessary. Closing.
