### ISSUE TITLE
Silver Harp should be changed or removed.

### ISSUE THREAD

**Issue by mcgrew** [mcgrew/dwrandomizer#6]
The silver harp does nothing other than take up inventory space right now. It should probably be either changed or removed.

**Comment by Jaylow7** [comment]
100% agree. In the current state of the randomizer, the silver harp is pretty much useless since you do not need to give it to the guy that wants it to collect the chest.

**Comment by mcgrew** [comment]
The latest code replaces the harp chest with a key.
