### ISSUE TITLE
Instructions/README

### ISSUE THREAD

**Issue by joshcough** [mcgrew/dwrandomizer#61]
Hi mcgrew,

Are there any instructions on how to run this? Maybe adding a simple README would help. I would really like to try this out, but don't know where to start.

Thank you,

-Josh

**Comment by mcgrew** [comment]
There was a README but it's outdated and was removed in the rewrite. I'll add another one soon.

**Comment by mcgrew** [comment]
There's a new README in the repo. 😊

**Comment by joshcough** [comment]
yay
