### ISSUE TITLE
Vanilla Overworld

### ISSUE THREAD

**Issue by Entroper** [mcgrew/dwrandomizer#63]
Would love to be able to play with the vanilla overworld again.  :)  As it is, I'm not sure what effect the "Randomize Enemy Zones" flag has, since they seem pretty randomized even when this is disabled (I had Demon Knights just outside the Tantegel safe zone).

**Comment by skins4thewin** [comment]
I second this, would be nice to have a checkbox to leave the overworld stock but be able to randomize all the other stuff.  Would be a nice nostalgic trip but with all the nice randomized features.  No reason that I can see to leave this out.

**Comment by Kronoan** [comment]
I concur! I want to try this please!

**Comment by mcgrew** [comment]
This is done and will be in 2.1.
