### ISSUE TITLE
Soft-lock with Breconnary/Charlock location and cursed items.

### ISSUE THREAD

**Issue by VampireValik** [mcgrew/dwrandomizer#67]
Randomizer version: 2.0.1
Seed: 33603824138597
Flags: CDFGMPRWZ

I just encountered a soft-lock due to using the Death Necklace. I made a menuing error against the Dragonlord and died. I was sent back to Tantegel but booted out as expected because of the curse. The problem was that both Charlock and Breconnary were located on the other side of the Swamp Cave and Swamp North was inside Tantegel. I had no way to remove the curse and no way to go back to Charlock.

It would be nice if a check was put into place to ensure that if Swamp North/South is located in Tantegel that either Charlock or Breconnary are accessible from the same continent as Tantegel to avoid this situation. If a check forces Charlock onto the same continent as Tantegel in this case it might also be necessary to have one other twon with an inn to recover MP, otherwise a different soft-lock is still possible (unless I'm mistaken and MP is restored even though health is not when the King kicks the player out).

**Comment by mcgrew** [comment]
I've implemented a fix for this. It will be in 2.0.6 (or 2.1).
