### ISSUE TITLE
Windows 10 Pro: dwrandomizer.exe is not able to launch correctly.

### ISSUE THREAD

**Issue by doomguy255** [mcgrew/dwrandomizer#7]
Windows 10 Pro x64
CPU: AMD FX-8350 Eight Core 4.03 GHz
RAM: 8 Gigs Gskill
Graphics: AMD Radeon HD 7800 series
DW Randomizer: 1.0-rc1 Windows EXE

When I drag and drop the rom to the exe file the only thing that happens I get the spinning blue circle next to my mouse cursor. Then Explorer.exe locks up and I have to open my task manager and close the process and restart it. I never get a command window or anything for the randomizer. I also don't get a randomized rom. The application does appear to be running in some capacity because when I attempt to delete the .exe file windows throws the "this application is still in use error." I can't seem to find any processes linking to it in my task manager though. At this point the randomizer is completely unusable to me. Also worth noting that when I just regularly double click the exe without dragging a rom to it the same thing happens. Also going to note it works fine through .py files so it's just the windows exe.
1. Open dwrandomizer.exe on a Win 10 Pro x64 machine.
2. Notice no windows open up and explore.exe locks up.

**Comment by mcgrew** [comment]
I'll try to look into this when I'm able. I don't have any access to a Windows 10 PC at this time (as it doesn't seem to run in Virtualbox), so it may take some time.

**Comment by gameboy9** [comment]
Overhearing a Zelda Randomizer stream, try running the program as an administrator.  I can't guarantee that will fix the issue, but hopefully it will help.

**Comment by mcgrew** [comment]
Agreed, I have a feeling this is a permissions problem, but I have no way to verify it.

**Comment by doomguy255** [comment]
I have run this as admin still the same issue. Sorry I didn't mention that to begin with.

**Comment by Kronoan** [comment]
I hope you get this issue figured out Doomguy!

**Comment by thasolidjake** [comment]
SO i fixed this on my end by running it in windows 7 compatability mode and as admin

**Comment by Entroper** [comment]
This probably doesn't help, but here's the Windows event log entry when this happens:

Faulting application name: DragonWarriorRandomizer.exe, version: 0.0.0.0, time stamp: 0x565a0480
Faulting module name: MSVCR100.dll, version: 10.0.40219.325, time stamp: 0x4df2be1e
Exception code: 0xc0000417
Fault offset: 0x0008af3e
Faulting process id: 0x317c
Faulting application start time: 0x01d224c087df06f6
Faulting application path: C:\Games\Dragon Warrior Randomizer\DragonWarriorRandomizer.exe
Faulting module path: C:\WINDOWS\SYSTEM32\MSVCR100.dll
Report Id: 26dd063e-334d-40bf-bbfd-88e71a19b0be
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Entroper** [comment]
That's a pretty old version of the C++ runtime (2010).  But I assume it's just what Python links against.

**Comment by mcgrew** [comment]
That may be the vc++ runtime version I have installed on the Windows 7 VM in using to compile this. I do finally have access to a Windows 10 machine now, so I'll try to revisit this issue soon.

**Comment by Entroper** [comment]
I tried googling for that exception code and various combinations of "python" and "Windows 10" but couldn't find anything that sounded right.  It's probably just some weird compatibility thing though, and moving to a newer redistributable might fix it.

**Comment by mcgrew** [comment]
Version 1.3 will work with Windows 10, as that's what I'm developing the Windows version on. Now to make sure it runs on older versions....

**Comment by mcgrew** [comment]
This is fixed in 1.3-rc1. Rejoice!
