### ISSUE TITLE
Remove the door to the Brecconary fairy water shop

### ISSUE THREAD

**Issue by mcgrew** [mcgrew/dwrandomizer#70]
This will make Brecconary more useful and give players another easy place to get fairy water. Nobody wants to burn a key to get it.

**Comment by gameboy9** [comment]
0x78A = 0x46 - Should turn the magic door into a brick walkway (which is what it is when you open the door)

**Comment by mcgrew** [comment]
Yeah it's a simple fix. I just created an issue so I wouldn't forget about it.

**Comment by gameboy9** [comment]
We also will need to change the wall a bit; the merchant, like the one in Cantlin, likes to check Facebook...

**Comment by mcgrew** [comment]
This has been done as of commit 4cb644f9
