### ISSUE TITLE
What's the difference between compiling using qmake against the moc and using cmake?

### ISSUE THREAD

**Issue by OmnipotentEntity** [mcgrew/dwrandomizer#74]
Is there a substantial difference?  Is there a good way to enable cli compilation other than manually defining -D DWR_CLI:Bool=True ?

**Comment by mcgrew** [comment]
There is no difference between the two. I started with cmake but found that it was difficult to compile the static binary for Windows without qmake, so I switched. I left the cmake file in place to allow compiling without installing Qt.

I modified CMakeLists to build the CLI version always, and build the GUI only if Qt is available.
