### ISSUE TITLE
Disallow metal slime encounters in early game

### ISSUE THREAD

**Issue by gameboy9** [mcgrew/dwrandomizer#76]
With consideration to the result of the 2nd game of the Grand Final, I think we should disallow any metal slime encounter until the hero has more than 20 strength, which is the limit to metal slimes running away.

Either that or have the metal slime have 1 or 2 strength or something silly like that to force it that way.

... or disallow encounters until level 6 is achieved?

**Comment by VartioArtel** [comment]
If it were me, I'd guarantee they had a risk-reward instead. Like obscenely high chance of DL2 breath or maybe if they don't roll that, then absurd base attack.

**Comment by Jaylow7** [comment]
Not sure exactly how to go about it but I agree something should be done. Last night's Grand Final game 2 was not the first race I've watched that was more or less decided because of the levels from a super early metal slime kill.

**Comment by mcgrew** [comment]
I have added an option to make metal slimes always afraid, e.g. they will always have a chance to run with this option on, regardless of player strength.
