### ISSUE TITLE
Minor Cosmetic Change Request:

### ISSUE THREAD

**Issue by VartioArtel** [mcgrew/dwrandomizer#77]
During the congratulations screen, it should say the following instead of "But there are many roads left to travel"

It should say:

"But thou did not save the animals... erm... Princess"
Or
"And thou saved the Animals... erm... Princess!"

**Comment by mcgrew** [comment]
I'll look into messing around with some of the text in future versions where appropriate, but this isn't in any immediate plans. Stay tuned.
