### ISSUE TITLE
Dragonlord 2 Stopspell Resistance

### ISSUE THREAD

**Issue by githubbalicious** [mcgrew/dwrandomizer#87]
Using v2.0.6  seed 10 flags CDGMPRVWXZ  Dragonlord 2 casts SLEEP and has a STOPSPELL resistance of 15/16 which is the max.    Not sure if this is a bug or within the intended range of randomization, but the changelog for v2.0 does imply STOPSPELL susceptibility if the dragonlord has HEAL or SLEEP.

**Comment by mcgrew** [comment]
I have lowered his resistance to a max of 14/16 in the latest beta. We'll see if that's better.
