### ISSUE TITLE
Occasional UI crash during map generation

### ISSUE THREAD

**Issue by mcgrew** [mcgrew/dwrandomizer#92]
I need to track this down, but first I need a seed number to reproduce it reliably.

**Comment by CaelThunderwing** [comment]
the seed number: 13923714059458252039
but testing the latest commit after cross compiling for windows in my linux VM via Wine, (before copying it out of the VM)i had it crash twice, once during map generation , then at patching credits, the error wine spat out both times: 

wine: Unhandled page fault on read access to 0x00000000 at address 0xf7c86c37 (thread 0009), starting debugger...

the output works normally in windows (did so for vooovits too) but both times it left no output for a rom, 
don't know if its the same issue but if it Is related i hope this somehow helps

**Comment by mcgrew** [comment]
Checked this out and it seems to be a wine-related bug. It works properly in my version of wine, so I'm closing this issue.

**Comment by mcgrew** [comment]
seed 139933333849664 reproduces this issue (on Linux at least)

**Comment by mcgrew** [comment]
This is fixed in 1187c2b
