### ISSUE TITLE
Allow REPEL in caves and permanent REPEL

### ISSUE THREAD

**Issue by gameboy9** [mcgrew/dwrandomizer#96]
First idea originally offered by Thilotilo.  To implement REPEL working in dungeons, make 0xCF34-0xCF35 equal to 0XEA, NOPing the overworld check.

The second idea was a cascade of Thilotilo's idea.  To implement REPEL being permanent, make 0xCF39-0xCF3A equal to 0xEA, NOPing the check to see if you have REPEL enabled.

**Comment by mcgrew** [comment]
This is an interesting idea.

**Comment by mcgrew** [comment]
Implemented in 0f912ed
